<?php

/**
 * BaseMembershipStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Memberships
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Doctrine_Collection getMemberships() Returns the current record's "Memberships" collection
 * @method MembershipStatus    setName()        Sets the current record's "name" value
 * @method MembershipStatus    setCreatedAt()   Sets the current record's "created_at" value
 * @method MembershipStatus    setUpdatedAt()   Sets the current record's "updated_at" value
 * @method MembershipStatus    setMemberships() Sets the current record's "Memberships" collection
 * 
 * @package    dksys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMembershipStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('membership_status');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Membership as Memberships', array(
             'local' => 'id',
             'foreign' => 'membership_status_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}