<?php

/**
 * BaseSeason
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $year
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Memberships
 * 
 * @method integer             getYear()        Returns the current record's "year" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Doctrine_Collection getMemberships() Returns the current record's "Memberships" collection
 * @method Season              setYear()        Sets the current record's "year" value
 * @method Season              setCreatedAt()   Sets the current record's "created_at" value
 * @method Season              setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Season              setMemberships() Sets the current record's "Memberships" collection
 * 
 * @package    dksys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeason extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('season');
        $this->hasColumn('year', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Membership as Memberships', array(
             'local' => 'id',
             'foreign' => 'season_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}