<?php

/**
 * BaseMembership
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_id
 * @property integer $season_id
 * @property integer $membership_type_id
 * @property integer $membership_status_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Member $Member
 * @property Season $Season
 * @property MembershipType $MembershipType
 * @property MembershipStatus $MembershipStatus
 * 
 * @method integer          getMemberId()             Returns the current record's "member_id" value
 * @method integer          getSeasonId()             Returns the current record's "season_id" value
 * @method integer          getMembershipTypeId()     Returns the current record's "membership_type_id" value
 * @method integer          getMembershipStatusId()   Returns the current record's "membership_status_id" value
 * @method timestamp        getCreatedAt()            Returns the current record's "created_at" value
 * @method timestamp        getUpdatedAt()            Returns the current record's "updated_at" value
 * @method Member           getMember()               Returns the current record's "Member" value
 * @method Season           getSeason()               Returns the current record's "Season" value
 * @method MembershipType   getMembershipType()       Returns the current record's "MembershipType" value
 * @method MembershipStatus getMembershipStatus()     Returns the current record's "MembershipStatus" value
 * @method Membership       setMemberId()             Sets the current record's "member_id" value
 * @method Membership       setSeasonId()             Sets the current record's "season_id" value
 * @method Membership       setMembershipTypeId()     Sets the current record's "membership_type_id" value
 * @method Membership       setMembershipStatusId()   Sets the current record's "membership_status_id" value
 * @method Membership       setCreatedAt()            Sets the current record's "created_at" value
 * @method Membership       setUpdatedAt()            Sets the current record's "updated_at" value
 * @method Membership       setMember()               Sets the current record's "Member" value
 * @method Membership       setSeason()               Sets the current record's "Season" value
 * @method Membership       setMembershipType()       Sets the current record's "MembershipType" value
 * @method Membership       setMembershipStatus()     Sets the current record's "MembershipStatus" value
 * 
 * @package    dksys
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMembership extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('membership');
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('season_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('membership_type_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('membership_status_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));


        $this->index('unique_membership', array(
             'fields' => 
             array(
              0 => 'member_id',
              1 => 'season_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Season', array(
             'local' => 'season_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MembershipType', array(
             'local' => 'membership_type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MembershipStatus', array(
             'local' => 'membership_status_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}