<?php

/**
 * MembershipTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MembershipTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MembershipTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MembershipType');
    }
}