<?php

/**
 * SeasonTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeasonTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeasonTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Season');
    }
}