<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/18 22:27:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dksys',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
