<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/07/18 23:24:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'sqlite:/Users/kara/Sites/dksys/db/db.sqlite',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
